// Mock data for admin dashboard

import ProjectsIcon from "../icons/ProjectsIcon";
import Species from "../icons/Species";
import TreesIcon from "../icons/TreesIcon";
import { AnalyticsCard, ChartDatum, RecentDonationRow } from "./dashboard/types";

export const analyticsCards: AnalyticsCard[] = [
  {
    id: 1,
    icon: ProjectsIcon,
    title: "Projects",
    value: 41,
    bgColor: "#F3F4F6",
  },
  {
    id: 2,
    icon: TreesIcon,
    title: "Trees",
    value: 4893,
    bgColor: "#F3F4F6",
  },
  {
    id: 3,
    icon: Species,
    title: "Species",
    value: 321,
    bgColor: "#F3F4F6",
  },
];

export const weeklyChartData: ChartDatum[] = [
  { day: "SUN", amount: 150000, fill: "#E5EBF5" },
  { day: "MON", amount: 180000, fill: "#E5EBF5" },
  { day: "TUE", amount: 100000, fill: "#E5EBF5" },
  { day: "WED", amount: 220000, fill: "#E5EBF5" },
  { day: "THU", amount: 190000, fill: "#E5EBF5" },
  { day: "FRI", amount: 160000, fill: "#E5EBF5" },
  { day: "SAT", amount: 345000, fill: "#95AAD5" },
];

export const monthlyChartData: ChartDatum[] = [
  { month: "JAN", amount: 210000, fill: "#E5EBF5" },
  { month: "FEB", amount: 180000, fill: "#E5EBF5" },
  { month: "MAR", amount: 240000, fill: "#E5EBF5" },
  { month: "APR", amount: 290000, fill: "#E5EBF5" },
  { month: "MAY", amount: 345000, fill: "#E5EBF5" },
  { month: "JUN", amount: 200000, fill: "#E5EBF5" },
  { month: "JUL", amount: 230000, fill: "#E5EBF5" },
  { month: "AUG", amount: 270000, fill: "#E5EBF5" },
  { month: "SEP", amount: 310000, fill: "#E5EBF5" },
  { month: "OCT", amount: 330000, fill: "#E5EBF5" },
  { month: "NOV", amount: 290000, fill: "#E5EBF5" },
  { month: "DEC", amount: 350000, fill: "#95AAD5" },
];

export const recentDonations: RecentDonationRow[] = [
  {
    id: 1,
    hrIdTo: "FBHPT345",
    name: "Kavita Bharti Vasani",
    trees: "Mango",
    donationFor: "SELF",
    donationForColor: "#0D824B",
    cat: "Species",
    geoTagged: true,
    currency: "INR",
    amount: 3454,
    fundUrl: "#",
  },
  {
    id: 2,
    hrIdTo: "FBHPT346",
    name: "Shivagath Project",
    trees: "Banana",
    donationFor: "GIFTED",
    donationForColor: "#F59E0B",
    cat: "Projects",
    geoTagged: false,
    currency: "INR",
    amount: 54684898,
    fundUrl: "#",
  },
  {
    id: 3,
    hrIdTo: "FBHPT347",
    name: "Kavita Bharti Vasani",
    trees: "Spade Wood",
    donationFor: "RECEIVED",
    donationForColor: "#641971",
    cat: "LightBox",
    geoTagged: true,
    currency: "INR",
    amount: 3454,
    fundUrl: "#",
  },
  {
    id: 4,
    hrIdTo: "FBHPT348",
    name: "Satna Project",
    trees: "Arjuna",
    donationFor: "GIFTED",
    donationForColor: "#F59E0B",
    cat: "Projects",
    geoTagged: true,
    currency: "INR",
    amount: 54684898,
    fundUrl: "#",
  },
  {
    id: 5,
    hrIdTo: "FBHPT349",
    name: "Kavita Bharti Vasani",
    trees: "Banyan",
    donationFor: "SELF",
    donationForColor: "#0D824B",
    cat: "LightBox",
    geoTagged: true,
    currency: "INR",
    amount: 3454,
    fundUrl: "#",
  },
  {
    id: 6,
    hrIdTo: "FBHPT350",
    name: "Green Earth Initiative",
    trees: "Neem",
    donationFor: "RECEIVED",
    donationForColor: "#641971",
    cat: "Species",
    geoTagged: false,
    currency: "INR",
    amount: 12500,
    fundUrl: "#",
  },
  {
    id: 7,
    hrIdTo: "FBHPT351",
    name: "Rahul Deshmukh",
    trees: "Peepal",
    donationFor: "SELF",
    donationForColor: "#0D824B",
    cat: "LightBox",
    geoTagged: true,
    currency: "INR",
    amount: 7800,
    fundUrl: "#",
  },
  {
    id: 8,
    hrIdTo: "FBHPT352",
    name: "Vidarbha Forest Drive",
    trees: "Teak",
    donationFor: "GIFTED",
    donationForColor: "#F59E0B",
    cat: "Projects",
    geoTagged: false,
    currency: "INR",
    amount: 230000,
    fundUrl: "#",
  },
  {
    id: 9,
    hrIdTo: "FBHPT353",
    name: "Anita Kulkarni",
    trees: "Jamun",
    donationFor: "SELF",
    donationForColor: "#0D824B",
    cat: "Species",
    geoTagged: true,
    currency: "INR",
    amount: 4200,
    fundUrl: "#",
  },
  {
    id: 10,
    hrIdTo: "FBHPT354",
    name: "Pune Riverfront Project",
    trees: "Ashoka",
    donationFor: "RECEIVED",
    donationForColor: "#641971",
    cat: "Projects",
    geoTagged: true,
    currency: "INR",
    amount: 985000,
    fundUrl: "#",
  },
];
